### ISSUE TITLE
Developer Docs Translation

### ISSUE THREAD

**Issue by zuorong-zhang** [elementary/docs#169]
### Problem

Now Developer Docs has no i18n system.

### Proposal

Create a project on [Elementary Weblate](https://l10n.elementary.io/projects/).

### Prior Art (Optional)

Create a project on Elementary Weblate like other Elementary apps.

**Comment by ryonakano** [comment]
Hi, thank you for your request! But we've decided that we no longer support translation on our developers documentation, because of its frequent modification and large quantity of strings to be translated. Also, these kind of things includes terms only well-known in software developers, so some translators who are not familiar with programming may misunderstand the meaning of these terms correctly and thus translate them in a wrong meaning.
