### ISSUE TITLE
Human Interface Guidelines: basic typographical guidelines

### ISSUE THREAD

**Issue by aral** [elementary/docs#52]
## Problem

I’m creating a new native app for elementary OS. I read the elementary OS Human Interface Guidelines. Confident in my newfound knowledge, I select Comic Sans as the font for my app and start coding.

## Proposal

Add information on typographical conventions to the Human Interface Guidelines. Off the top of my head:

  - What is the system font?
  - What is the system monospace font?
  - What font sizes are recommended for various interface elements, including body and display type?
  - What font weights are recommended for various interface elements?
  - What’s the recommended line spacing? 
  - Are there predefined styles that can/should be used?

**Comment by danrabbit** [comment]
Right so this is definitely not a normal case since an app in AppCenter wouldn't have access to the window manager. They can probably get a pango font description from GtkStyleContext using the foreign drawing API, but again this is not a normal case and no AppCenter developer should ever have to do that.

The problem is there is no one single system font. Apps need to respond if a user selects dyslexia-friendly fonts or if the screenshot tool requests the redacted script and they also need to adapt to scaling.

If you're using Gtk (which is a requirement for publishing in AppCenter), the toolkit handles font styles automatically. You don't have to do anything. So this information isn't really relevant for app developers publishing in AppCenter

**Comment by aral** [comment]
Right, that sounds good and makes sense but surely there are a set of default fonts, right? Where can I find that information, if only so I know what they are?

**Comment by danrabbit** [comment]
Yeah, there's the default settings repo here: https://github.com/elementary/default-settings/blob/ff9a432dada00bfeadcb3c423e6cfbfd1c90f978/overrides/default-settings.gschema.override.in#L27

**Comment by aral** [comment]
Cool, thanks, Daniel. Hope you’re having a lovely end of year.

🎄☃️❄️
